import React from 'react';
import './AboutUs.css'; // We'll create this

const AboutUs = () => {
  return (
    <div className="about-us-container dash-card">
      <h2>About This Project</h2>
      <p>
        This platform is an AI-Powered Student Growth & Performance Analytics System, 
        developed as a 3rd-Year B.Tech project.
      </p>
      
      <h3>Objective</h3>
      <p>
        The primary goal is to move beyond traditional academic evaluation. This system 
        provides a 360-degree insight into a student's progress by combining:
      </p>
      <ul>
        <li>Academic Performance (GPA, Attendance)</li>
        <li>Technical Skill Development (LeetCode, GitHub)</li>
        <li>Extracurricular Achievements (Events, Volunteering)</li>
      </ul>

      <h3>Technology Stack</h3>
      <p>
        This application is built as a full-stack, distributed system:
      </p>
      <ul>
        <li><strong>Frontend:</strong> React.js, Vite, Chart.js, Axios</li>
        <li><strong>Backend (API):</strong> Node.js, Express.js, MongoDB</li>
        <li><strong>Authentication:</strong> JSON Web Tokens (JWT)</li>
        <li><strong>Machine Learning (Microservice):</strong> Python, Flask, Pandas, Scikit-learn</li>
      </ul>

      <h3>Core Feature: The Growth Index</h3>
      <p>
        The "Growth Index" score is not a static number. It is a live prediction 
        generated by a machine learning model. This model analyzes your current data 
        and predicts your overall growth trajectory.
      </p>
    </div>
  );
};

export default AboutUs;